## 12.2	“array” 패키지 사용하기

In [1]:
import array

In [2]:
a = array.array('h', [1, 2, 3])
a

array('h', [1, 2, 3])

In [3]:
a = array.array('h', range(1000))
a

array('h', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219

In [4]:
a = array.array('l', range(1_000_000))

## 12.4 numpy 소개하기: 1부터 100만까지 더하기

In [5]:
import numpy as np

In [6]:
a_list = list(range(1, 1_000_001))
print(sum(a_list))

500000500000


In [7]:
a = np.arange(1, 1_000_001)
print(sum(a))

1784293664


C:\Users\gilbut\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in long_scalars
  


In [8]:
import numpy as np
from time import time

def benchmarks(n):
    t1 = time()

    a_list = list(range(1, n + 1)) 	# Old style!
    tot = sum(a_list)

    t2 = time()
    print('Time taken by Python is', t2 - t1)
    t1 = time()

    a = np.arange(1, n + 1) 		# Numpy!
    tot = np.sum(a)

    t2 = time()
    print('Time taken by numpy is ', t2 - t1)

In [9]:
benchmarks(10_000_000)

Time taken by Python is 0.36003923416137695
Time taken by numpy is  0.01546478271484375


## 12.5	numpy 배열 만들기

### 12.5.1	<중> array 함수 (array로 변환)

In [10]:
import numpy as np
a = np.array([1, 2, 3])

In [11]:
a = np.array([[1, 2, 3], [10, 20, 30], [0, 0, -1]])
print(a)

[[ 1  2  3]
 [10 20 30]
 [ 0  0 -1]]


In [12]:
a = np.array([[1, 2, 3], [10, 20, 300]])
a

array([[  1,   2,   3],
       [ 10,  20, 300]])

In [13]:
a = np.array([[1, 2, 3], [10, 20, 300, 4]])
a

C:\Users\gilbut\anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3]), list([10, 20, 300, 4])], dtype=object)

### 12.5.2 arange 함수

In [14]:
import numpy as np
a = np.arange(1, 1000001) 	# 100만개 항목으로 구성된 배열 생성

### 12.5.3	linspace 함수

In [15]:
import numpy as np
a = np.linspace(0, 1.0, num=5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
a = np.linspace(0, 1.0, num=6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
np.linspace(1, 5, num=5, dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int16)

### 12.5.4 empty 함수

In [18]:
import numpy as np
a = np.empty((2, 2), dtype='int16')
a

array([[    0,     0],
       [    0, 16368]], dtype=int16)

In [19]:
a = np.empty((3, 2), dtype='float32')
a

array([[3.3454865e+31, 8.6880505e-43],
       [0.0000000e+00, 0.0000000e+00],
       [1.8367379e-40,           nan]], dtype=float32)

### 12.5.5	eye 함수

In [20]:
a = np.eye(4, dtype='int')
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [21]:
a = np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### 12.5.6 ones 함수

In [22]:
import numpy as np
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a = np.ones((2, 2, 3), dtype=np.int16)
a

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [24]:
a = np.ones(6, dtype=np.bool)
a

array([ True,  True,  True,  True,  True,  True])

### 12.5.7	zeros 함수

In [25]:
import numpy as np
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
a = np.zeros((2, 2, 3), dtype=np.int16)
a

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [27]:
a = np.zeros(5, dtype=np.bool)
a

array([False, False, False, False, False])

### 12.5.8 full 함수

In [28]:
import numpy as np
a = np.full((2, 2), 3.14)
a

array([[3.14, 3.14],
       [3.14, 3.14]])

In [29]:
a = np.full(8, 100)
a

array([100, 100, 100, 100, 100, 100, 100, 100])

In [30]:
a = np.full(5,'ken')
a

array(['ken', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

In [31]:
a[0] = 'tommy'
a[0]

'tom'

### 12.5.9 copy 함수

In [32]:
import numpy as np
b_arr = np.copy(a)
b_arr

array(['tom', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

### 12.5.10 fromfunction 함수

In [33]:
import numpy as np

def simple(n):
    return n + 1

a = np.fromfunction(simple, (5,), dtype='int32')
a

array([1, 2, 3, 4, 5])

In [34]:
a = np.fromfunction(lambda n:n+1, (5,), dtype='int32')
a

array([1, 2, 3, 4, 5])

In [35]:
def add_it(r, c):
    return r + c

a = np.fromfunction(add_it, (3, 3), dtype='int32')
a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [36]:
a = np.fromfunction(lambda r,c:r+c, (3, 3), dtype='int')
a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [37]:
a = np.fromfunction(lambda r, c: 1, (3, 3), dtype='int')
a

1

## 12.6	예시:  곱셈표 만들기

In [38]:
import numpy as np

def multy(r, c):
    return (r + 1) * (c+ 1)

a = np.fromfunction(multy, (10, 10), dtype=np.int16)
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [39]:
a = np.fromfunction(lambda r,c: (r+1) * (c+1), (10, 10), dtype=np.int16)
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [40]:
s = str(a)
s = s.replace('[', '')
s = s.replace(']', '')
s = ' ' + s

In [41]:
print(s)

   1   2   3   4   5   6   7   8   9  10
   2   4   6   8  10  12  14  16  18  20
   3   6   9  12  15  18  21  24  27  30
   4   8  12  16  20  24  28  32  36  40
   5  10  15  20  25  30  35  40  45  50
   6  12  18  24  30  36  42  48  54  60
   7  14  21  28  35  42  49  56  63  70
   8  16  24  32  40  48  56  64  72  80
   9  18  27  36  45  54  63  72  81  90
  10  20  30  40  50  60  70  80  90 100


## 12.7 numpy 배열의 배치 연산

In [42]:
import numpy as np

A = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [43]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
A = np.fromfunction(lambda r, c: r*4 + c, (4, 4))
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [45]:
B = np.eye(4, dtype='int16')
print(B)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [46]:
C = A * 10
print(C)

[[  0.  10.  20.  30.]
 [ 40.  50.  60.  70.]
 [ 80.  90. 100. 110.]
 [120. 130. 140. 150.]]


In [47]:
C = A * A
print(C)

[[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]
 [144. 169. 196. 225.]]


In [48]:
print(C.reshape((2,8)))

[[  0.   1.   4.   9.  16.  25.  36.  49.]
 [ 64.  81. 100. 121. 144. 169. 196. 225.]]


In [49]:
C = A * B
print(C)

[[ 0.  0.  0.  0.]
 [ 0.  5.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 15.]]


## 12.8 numpy의 조각을 정렬하기

In [50]:
A = np.arange(1, 11)
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
print(A[2:5])

[3 4 5]


In [52]:
A[2:5] = 0
print(A)

[ 1  2  0  0  0  6  7  8  9 10]


In [53]:
A[2:5] += 100
print(A)

[  1   2 100 100 100   6   7   8   9  10]


In [54]:
A = np.arange(1, 11)
A[2:5] *= [100, 200, 300]
A

array([   1,    2,  300,  800, 1500,    6,    7,    8,    9,   10])

In [55]:
A = np.arange(51)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [56]:
A[1] = 0
A[2 * 2::2] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23
  0 25  0 27  0 29  0 31  0 33  0 35  0 37  0 39  0 41  0 43  0 45  0 47
  0 49  0]


In [57]:
A[3 * 3::3] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  0  0 11  0 13  0  0  0 17  0 19  0  0  0 23
  0 25  0  0  0 29  0 31  0  0  0 35  0 37  0  0  0 41  0 43  0  0  0 47
  0 49  0]


In [58]:
A[5 * 5::5] = 0
A[7 * 7::7] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  0  0 11  0 13  0  0  0 17  0 19  0  0  0 23
  0  0  0  0  0 29  0 31  0  0  0  0  0 37  0  0  0 41  0 43  0  0  0 47
  0  0  0]


In [59]:
my_prime_list = [i for i in A if i > 0]

In [60]:
P = A[A > 0]
print(P)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


## 12.9 다차원 슬라이싱

In [61]:
A = np.arange(1,17).reshape((4,4))
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [62]:
print(A[1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
A[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [64]:
G = np.zeros((6, 6))
G[1:4, 2] = 1
print(G)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [65]:
print(G[1:4, 1:4])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


## 12.10	불리언 배열: 넘파이에 마스킹하기!

In [66]:
B = np.arange(1,10).reshape(3,3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
B1 = B > 4
B1

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [68]:
print(B * (B > 4))

[[0 0 0]
 [0 5 6]
 [7 8 9]]


In [69]:
print(B[B > 7])

[8 9]


In [70]:
print(B[B % 3 == 1])

[1 4 7]


In [71]:
B2 = (B > 2) & (B < 7) 		# "AND" 연산
print(B2)

[[False False  True]
 [ True  True  True]
 [False False False]]


In [72]:
print(B[B2])

[3 4 5 6]


In [73]:
print(B[ (B == 1) | (B > 6)]) 	# ‘OR’ 연산자

[1 7 8 9]


## 12.11 numpy와 에라토스테네스의 체

In [74]:
def sieve(n):
    b_list = [True] * (n + 1)
    for i in range(2, n+1):
        if b_list[i]:
            for j in range(i*i, n+1, i):
                b_list[j] = False
    primes = [i for i in range(2, n+1) if b_list[i]]
    return primes

In [75]:
import numpy as np

def np_sieve(n):
    # B 생성, 모든 항목을 True로 설정한다.
    B = np.ones(n + 1, dtype=np.bool)
    B[0:2] = False
    for i in range(2, n + 1):
        if B[i]:
            B[i*i: n+1: i] = False
    return np.arange(n + 1)[B]

In [76]:
import numpy as np
import time

def np_sieve(n):
    t1 = time.time() * 1000
    B = np.ones(n + 1, dtype=np.bool)
    B[0:2] = False
    for i in range(2, n + 1):
        if B[i]:
            B[i*i: n+1: i] = False
    P = np.arange(n + 1)[B]
    t2 = time.time() * 1000
    print('np_sieve took', t2-t1, 'milliseconds.')

## 12.12 numpy 통계 구하기 – 표준 편차

In [77]:
import numpy as np
import numpy.random as ran
A = ran.rand(10)
print(A)

[0.47334369 0.29932661 0.01390954 0.14543423 0.33398205 0.74158583
 0.86116044 0.70661806 0.5771554  0.18573483]


In [78]:
A = ran.rand(100000)

In [79]:
import numpy as np
import numpy.random as ran
A = ran.random(100000)
np.mean(A)

0.500963797652034

In [80]:
np.sum(A)

50096.3797652034

In [81]:
np.median(A)

0.5005040226652013

In [82]:
np.std(A)

0.2891668026843425

In [83]:
import numpy as np
import time
import numpy.random as ran

def get_std1(ls):
    t1 = time.time()
    m = sum(ls)/len(ls)
    ls2 = [(i - m) ** 2 for i in ls]
    sd = (sum(ls2)/len(ls2)) ** .5
    t2 = time.time()
    print('Python took', t2-t1)

def get_std2(A):
    t1 = time.time()
    A2 = (A - np.mean(A)) ** 2
    result = (np.mean(A2)) ** .5
    t2 = time.time()
    print('Numpy took', t2-t1)

def get_std3(A):
    t1 = time.time()
    result = np.std(A)
    t2 = time.time()
    print('np.std took', t2-t1)

A = ran.rand(1000000)
get_std1(A)
get_std2(A)
get_std3(A)

Python took 0.697655200958252
Numpy took 0.006978034973144531
np.std took 0.004987478256225586


## 12.13 numpy 행과 열 가져오기

In [84]:
import numpy as np
import numpy.random as ran
A = ran.randint(1, 20, (3, 4))
print(A)

[[ 4 14 15  7]
 [16 19 16  5]
 [ 8 16 12 15]]


In [85]:
np.mean(A)

12.25

In [86]:
np.sum(A)

147

In [87]:
np.std(A) 		# 표준 편차

4.763139720814412

In [88]:
B = np.fromfunction(lambda r,c: c, (4, 5), dtype=np.int32)
print(B)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [89]:
np.sum(B, axis = 0) 		# 행, 열의 합계.

array([ 0,  4,  8, 12, 16])

In [90]:
np.sum(B, axis = 1) 		# 열, 행의 합계.

array([10, 10, 10, 10])

In [91]:
B = np.fromfunction(lambda r,c:c, (4, 5), dtype=np.int32)
print(B)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [92]:
B_rows = np.sum(B, axis = 1)
B_rows

array([10, 10, 10, 10])

In [93]:
B1 = np.c_[B, B_rows]
print(B1)

[[ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]]


In [94]:
B_cols = np.sum(B1, axis = 0)
B_cols

array([ 0,  4,  8, 12, 16, 40])

In [95]:
B2 = np.r_[B1, [B_cols]]
print(B2)

[[ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  4  8 12 16 40]]


In [96]:
def spreadsheet(A):
    AC = np.sum(A, axis = 1)
    A2 = np.c_[A, AC]
    AR = np.sum(A2, axis = 0)
    return np.r_[A2, [AR] ]

In [97]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [98]:
print(spreadsheet(arr))

[[  0   1   2   3   4  10]
 [  5   6   7   8   9  35]
 [ 10  11  12  13  14  60]
 [ 15  18  21  24  27 105]]
